### PR TITLE
Prevent shadowing of ___bisect_visit___

### LINKED ISSUE #160: Index out of bounds caused by the new source code
This isn't really a complete bug report, more a reminder to self to fix it later. If someone would like details, please ask.

The development version of Bisect_ppx, applied to Markup.ml, causes a failure with index out of bounds.

### PR DESCRIPTION
**Pull request by aantron**
See the large comment added by this commit to the code, and https://github.com/aantron/bisect_ppx/issues/160.

This commit also improves location information attached to the code generated at the top of each compilation unit. In particular, the name of the input file is preserved, instead of using "`_none_`".

Most of the diff is updated reference files for the test cases.

Fixes #160.

### CODE REVIEW

**Comment by rleonid** [comment]
This is cool!

**Comment by aantron** [comment]
Thanks :) I took that as a LGTM. You're welcome to object, and we can make any further modifications over `master`.

I'm going to get the 1.3.1 release into OPAM.

**Comment by aantron** [comment]
...or perhaps not, seems the tests weren't running in CI. Might have a few more bugs to fix, but I think they are nits (differences in Pprintast output). I'll just push to `master` and release, unless I find something serious.

**Comment by rleonid** [comment]
Living dangerously. I'm liking this new anything-goes @aantron !

**Comment by aantron** [comment]
Haha, yeah I've been reducing, over the last 6 months, the number of CI round trips I do. I even sometimes commit to `master` on Lwt, when feeling confident, then end up having to force-push it out :p

I figure it helps me (or other maintainer!) be efficient, but hurts nobody, since nobody is actually syncing with `master` on Bisect_ppx the vast majority of the time :)

**Pull request merged**
