### PR TITLE
Remove the manual call to driver

### PR DESCRIPTION
**Pull request by rgrinberg**
Since the project is a ppx_rewriter, dune will generate a ppx.exe that will
invoke the registered transformation already. This can be tested by running:

_build/install/default/lib/bisect_ppx/ppx.exe --as-ppx

Signed-off-by: Rudi Grinberg <rudi.grinberg@gmail.com>

### CODE REVIEW

**Comment by rgrinberg** [comment]
@aantron i can't seem to run the tests. I get errors like:

```
--- fixtures/instrument/expr_for.reference.ml
+++ actual output
@@ -1,3 +1,4 @@
+findlib: [WARNING] Package bisect_ppx has multiple definitions in ../../../../install/default/lib/bisect_ppx/META, /Users/rgrinberg/.opam/4.06.1/lib/bisect_ppx/META
 module Bisect_visit___expr_for___ml =
   struct
     let ___bisect_visit___ =

------------------------------------------------------------------------------
==============================================================================
Error: bisect_ppx:1:fixtures/instrument:1:expr_while.

File "/Users/rgrinberg/reps/ml/bisect_ppx/_build/default/test/unit/oUnit-bisect_ppx-Rudis-MBP#00.log", line 93, characters 1-1:
Error: bisect_ppx:1:fixtures/instrument:1:expr_while (in the log).

File "test/unit/test_helpers.ml", line 99, characters 1-1:
Error: bisect_ppx:1:fixtures/instrument:1:expr_while (in the code).

Difference against 'fixtures/instrument/expr_while.reference.ml':

--- fixtures/instrument/expr_while.reference.ml
+++ actual output
@@ -1,3 +1,4 @@
+findlib: [WARNING] Package bisect_ppx has multiple definitions in ../../../../install/default/lib/bisect_ppx/META, /Users/rgrinberg/.opam/4.06.1/lib/bisect_ppx/META
 module Bisect_visit___expr_while___ml =
   struct
     let ___bisect_visit___ =

------------------------------------------------------------------------------
==============================================================================
Error: bisect_ppx:1:fixtures/instrument:0:expr_binding.

File "/Users/rgrinberg/reps/ml/bisect_ppx/_build/default/test/unit/oUnit-bisect_ppx-Rudis-MBP#00.log", line 68, characters 1-1:
Error: bisect_ppx:1:fixtures/instrument:0:expr_binding (in the log).

File "test/unit/test_helpers.ml", line 99, characters 1-1:
Error: bisect_ppx:1:fixtures/instrument:0:expr_binding (in the code).

Difference against 'fixtures/instrument/expr_binding.reference.ml':

--- fixtures/instrument/expr_binding.reference.ml
+++ actual output
@@ -1,3 +1,4 @@
+findlib: [WARNING] Package bisect_ppx has multiple definitions in ../../../../install/default/lib/bisect_ppx/META, /Users/rgrinberg/.opam/4.06.1/lib/bisect_ppx/META
 module Bisect_visit___expr_binding___ml =
   struct
     let ___bisect_visit___ =

------------------------------------------------------------------------------
Ran: 45 tests in: 3.34 seconds.
FAILED: Cases: 45 Tried: 45 Errors: 2 Failures: 27 Skip:  3 Todo: 0 Timeouts: 0.
make: *** [test] Error 1
```

Am I goofing something?

**Comment by aantron** [comment]
@rgrinberg Looks like you have `bisect_ppx` installed in your switch. I suggest `opam remove bisect_ppx` while running the tests.

Looks fine in CI, though.

**Comment by rgrinberg** [comment]
I see. A check for the availability of bisect would be useful before running anything here.

Btw, why is the global bisect getting the way? You should be able to setup the tests in such a way that only the local bisect is. This is how we test findlib compatibility with dune generated META files for example.

**Comment by aantron** [comment]
It's just `ocamlfind` printing a warning, which ends up in the diffs we compare. I'm not immediately sure how to get it to stop looking in the opam path, which is part of the configuration of `ocamlfind` installed by opam.

**Comment by aantron** [comment]
Thanks! Sorry for delay.

**Pull request merged**
